// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4wQUUQq41cBzYmNz4TocV9wRTJcqg-X8',
    appId: '1:850410387723:web:f53e2e1ec8fce192590a0e',
    messagingSenderId: '850410387723',
    projectId: 'quickads-6798e',
    authDomain: 'quickads-6798e.firebaseapp.com',
    storageBucket: 'quickads-6798e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcMCVoGAEbpIsEJ7CkYYrEu5lZo1BaN-I',
    appId: '1:850410387723:android:0e1438e7d962a11d590a0e',
    messagingSenderId: '850410387723',
    projectId: 'quickads-6798e',
    storageBucket: 'quickads-6798e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbvx9olv23PxKoD9NcAB-o2rhWD-zWQw',
    appId: '1:850410387723:ios:5a758c721a6464b9590a0e',
    messagingSenderId: '850410387723',
    projectId: 'quickads-6798e',
    storageBucket: 'quickads-6798e.firebasestorage.app',
    iosBundleId: 'com.example.skriptarnica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApbvx9olv23PxKoD9NcAB-o2rhWD-zWQw',
    appId: '1:850410387723:ios:5a758c721a6464b9590a0e',
    messagingSenderId: '850410387723',
    projectId: 'quickads-6798e',
    storageBucket: 'quickads-6798e.firebasestorage.app',
    iosBundleId: 'com.example.skriptarnica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4wQUUQq41cBzYmNz4TocV9wRTJcqg-X8',
    appId: '1:850410387723:web:cd18bd2ab09da220590a0e',
    messagingSenderId: '850410387723',
    projectId: 'quickads-6798e',
    authDomain: 'quickads-6798e.firebaseapp.com',
    storageBucket: 'quickads-6798e.firebasestorage.app',
  );
}
